# SPDX-FileCopyrightText: 2022 Contributors to the rez project
#
# SPDX-License-Identifier: Apache-2.0

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
