# SPDX-FileCopyrightText: 2022 Contributors to the rez project
#
# SPDX-License-Identifier: Apache-2.0

name: docs

on:
  pull_request:
    paths:
    - '**/CHANGELOG.md'
    - 'docs/**'
    - '.github/workflows/docs.yaml'

permissions: {}

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: 'recursive'
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r docs/requirements.txt .

    - name: Linkcheck
      working-directory: docs
      run: |
        source ../.venv/bin/activate

        set +e
        make linkcheck
        exit_code=$?

        set -e

        if [ $exit_code -eq 0 ]; then
            echo -e "\n\n=================\nAll links are valid!"

            echo "# :heavy_check_mark: Sphinx links" >> $GITHUB_STEP_SUMMARY
            echo "All links are valid!" >> $GITHUB_STEP_SUMMARY
        else
            echo -e "\n\n=================\nFound broken links. Look at the build logs.\n"

            echo "# :x: Sphinx links" >> $GITHUB_STEP_SUMMARY
            echo "Found broken links. Look at the build logs for additional information." >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat build/linkcheck/output.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
        fi

        exit $exit_code

  check-warnings:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: 'recursive'
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r docs/requirements.txt .

    - name: Check warnings/errors
      working-directory: docs
      run: |
        source ../.venv/bin/activate

        set +e
        make htmlstrict

        exit_code=$?

        set -e

        if [ $exit_code -eq 0 ]; then
            echo -e "\n\n=================\nNo warnings or errors detected!"
            echo "# :heavy_check_mark: Sphinx warnings/errors" >> $GITHUB_STEP_SUMMARY
            echo "No errors or warnings detected!" >> $GITHUB_STEP_SUMMARY
        else
            echo -e "\n\n=================\nWarnings and or errors detected; See the summary bellow:\n"
            cat build/htmlstrict/output.txt

            echo "# :x: Sphinx warnings/errors" >> $GITHUB_STEP_SUMMARY
            echo "Found some warnings or errors:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat build/htmlstrict/output.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
        fi

        exit $exit_code
